### ISSUE TITLE
Business Plan

### ISSUE THREAD

**Issue by sbajjuri** [sbajjuri/Fusion#1]
Business plan have been discussed and written by everyone in the group. 

Executive Summary: Santosh, Nikhil: Due Date- 18th February 2016
Company Description: Bharath Bhushan Reddy Goulla: Due Date- 18th February 2016
Market Analysis: Vishal, Mahender: Due Date- 18th February 2016
Organization and Management: Nandini: Due Date- 18th February 2016
Service or Product Line: Manasa Kothakapu: Due Date- 18th February 2016
Marketing and Sales: Sai Charan Devtha: Due Date- 18th February 2016
Funding request: Sarika Pammi: Due Date- 18th February 2016
Financial Projections: Mobin Abdul: Due Date- 18th February 2016
How to make your business plan stand out: Due Date- 18th February 2016

**Comment by VISHALKAMTAM** [comment]
Working on it! Will submit it on time.

**Comment by bhushanreddy** [comment]
Will do my part asap and submit in google docx!

**Comment by kattenikhil** [comment]
I have sent the reference link to every one in de group regarding the working algorithm . Please check it out !!

**Comment by manasakothakapu** [comment]
started exploring trello.

**Comment by sbajjuri** [comment]
created lists (backlogs, analysis, in-dev, testing, code review, accepted) and added two story cards in the backlogs (requirements, prototype designing).... if you would take a deeper look about that, I would be thankful!. Thankful--

**Comment by RajaNandini** [comment]
Knowing about Trello and how it wil be useful for our fusion.

**Comment by manasakothakapu** [comment]
Knowing about story boards and its use with @saicharan123

**Comment by VISHALKAMTAM** [comment]
I have submitted the requirements for the project in the story board of trello which may be useful for our business plan.

**Comment by VISHALKAMTAM** [comment]
I am currently working on the market analysis for our business plan.Hope I would complete it and submit it as early as possible.
